name: Build and Push Docker Images

on:
    schedule:
        - cron: "0 2 * * 1"
    workflow_dispatch:

jobs:
    build:
        permissions:
            contents: read
            packages: write
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to GHCR
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and Push All Dockerfiles
              run: |
                for file in ./dockerfiles/*; do
                    image_name=$(basename $file)
                    docker build -f "$file" -t "ghcr.io/${{ github.repository_owner }}/${image_name}:latest" .
                    docker push "ghcr.io/${{ github.repository_owner }}/${image_name}:latest"
                done